"""empty message

Revision ID: 63af83625d10
Revises: 8d037477ed2c
Create Date: 2025-01-15 19:24:20.717382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63af83625d10'
down_revision = '8d037477ed2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('especialistas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=200), nullable=True))
        batch_op.drop_column('descripción')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('especialistas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripción', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
