"""empty message

Revision ID: 83a9ae3f88b1
Revises: 63af83625d10
Create Date: 2025-01-17 13:52:46.485461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a9ae3f88b1'
down_revision = '63af83625d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
