"""empty message

Revision ID: 891d66de799b
Revises: a8b78f68a76d
Create Date: 2025-01-17 14:37:15.841643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '891d66de799b'
down_revision = 'a8b78f68a76d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.alter_column('appointment_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('appointment_time',
               existing_type=postgresql.TIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.alter_column('appointment_time',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('appointment_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
