"""empty message

Revision ID: a8b78f68a76d
Revises: 83a9ae3f88b1
Create Date: 2025-01-17 13:57:26.203215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b78f68a76d'
down_revision = '83a9ae3f88b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
